import { ChartColumnBigIcon } from 'lucide-react';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <nav className="bg-primary p-4 text-white h-20 flex items-center justify-between">
          <Link href="/" className="text-2xl font-bold flex gap-1 items-center">
            <ChartColumnBigIcon className="text-lime-700" /> 42cents
          </Link>
          auth button
        </nav>
        {children}
      </body>
    </html>
  );
}
