import { ChartColumnBigIcon } from 'lucide-react';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import Link from 'next/link';
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignOutButton,
  SignUpButton,
} from '@clerk/nextjs';
import { UserDropdown } from '@/components/user-dropdown';
import { Button } from '@/components/ui/button';
import './globals.css';

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${poppins.variable} antialiased`}>
          <nav className="bg-primary p-4 text-white h-20 flex items-center justify-between">
            <Link
              href="/"
              className="text-2xl font-bold flex gap-1 items-center"
            >
              <ChartColumnBigIcon className="text-lime-700" /> 42cents
            </Link>
            <SignedOut>
              <div className="flex items-center">
                <Button asChild variant="link" className="text-white">
                  <SignInButton />
                </Button>
                <Button asChild variant="link" className="text-white">
                  <SignUpButton />
                </Button>
              </div>
            </SignedOut>
            <SignedIn>
              <Button asChild variant="link" className="text-white">
                <UserDropdown />
              </Button>
            </SignedIn>
          </nav>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
